import { useState } from "react";
import type { ModelProvider } from "../../domain/models";
import { getSecret, secretStorageMode } from "../../infrastructure/secret-store";
import { createAdapterForProfile, loadModelProfiles, removeModelProfile, saveModelProfile, type ModelProfile } from "../../application/model/model-profile";

export function ModelSettingsWorkspace({ profiles, activeId, onSelect, onTest, storageMode = secretStorageMode }: { profiles: readonly ModelProfile[]; activeId?: string; onSelect: (id: string) => void; onTest?: (profile: ModelProfile) => void; storageMode?: string }) {
  const [editing, setEditing] = useState<ModelProfile | null>(null);
  const [form, setForm] = useState({ name: "", provider: "openai-compatible" as ModelProvider, baseUrl: "https://api.openai.com/v1", modelName: "", apiKey: "", wireApi: "chat-completions" as "chat-completions" | "responses" });
  const [message, setMessage] = useState("");
  const begin = (profile?: ModelProfile) => { setEditing(profile ?? null); setMessage(""); setForm(profile ? { name: profile.name, provider: profile.provider, baseUrl: profile.baseUrl, modelName: profile.modelName, apiKey: "", wireApi: profile.wireApi ?? "chat-completions" } : { name: "新 API 配置", provider: "openai-compatible", baseUrl: "https://api.openai.com/v1", modelName: "", apiKey: "", wireApi: "chat-completions" }); };
  const save = async () => { const saved = await saveModelProfile(form, editing?.id); onSelect(saved.id); setEditing(saved); setMessage("配置已保存"); };
  const test = async () => { try { const saved = await saveModelProfile(form, editing?.id); const key = await getSecret(`model-profile:${saved.id}:api-key`); void key; const result = await (await createAdapterForProfile(saved)).testConnection(); setMessage(`连接成功：${result.message}`); } catch (error) { setMessage(`连接失败：${error instanceof Error ? error.message : "未知错误"}`); } };
  const remove = async () => { if (!editing) return; await removeModelProfile(editing.id); onSelect(loadModelProfiles()[0]?.id ?? ""); setEditing(null); setMessage("配置已删除"); };
  return <section className="model-settings-workspace" aria-label="模型配置"><div className="section-heading"><strong>模型配置</strong><span>{storageMode === "memory-fallback" ? "API Key 仅保存在当前会话" : "系统安全存储"}</span></div>{profiles.map((profile) => <article className={profile.id === activeId ? "profile-row selected" : "profile-row"} key={profile.id}><button type="button" onClick={() => onSelect(profile.id)}><strong>{profile.name}</strong><small>{profile.provider} · {profile.modelName} · {profile.hasApiKey ? "已配置密钥" : "无需密钥"}</small></button>{onTest && <button type="button" className="secondary-button" onClick={() => { begin(profile); onTest(profile); }}>测试连接</button>}</article>)}<div className="panel-actions"><button type="button" onClick={() => begin()}>新增 API 配置</button>{activeId && <button type="button" className="secondary-button" onClick={() => begin(profiles.find((profile) => profile.id === activeId))}>编辑当前配置</button>}</div>{(editing || form.name === "新 API 配置") && <div className="model-form"><label>配置名称<input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>供应商<select value={form.provider} onChange={(event) => setForm({ ...form, provider: event.target.value as ModelProvider })}><option value="ollama">Ollama</option><option value="openai-compatible">OpenAI-compatible</option></select></label><label>Base URL<input value={form.baseUrl} onChange={(event) => setForm({ ...form, baseUrl: event.target.value })} /></label><label>模型名称<input value={form.modelName} onChange={(event) => setForm({ ...form, modelName: event.target.value })} /></label>{form.provider === "openai-compatible" && <><label>API Key<input type="password" autoComplete="new-password" value={form.apiKey} onChange={(event) => setForm({ ...form, apiKey: event.target.value })} /></label><label>接口协议<select value={form.wireApi} onChange={(event) => setForm({ ...form, wireApi: event.target.value as "chat-completions" | "responses" })}><option value="chat-completions">Chat Completions</option><option value="responses">Responses</option></select></label></>}{message && <p className="form-status" role="status">{message}</p>}<div className="form-actions"><button type="button" onClick={() => void test()}>测试连接</button><button type="button" onClick={() => void save()}>保存配置</button>{editing && <button type="button" className="danger-button" onClick={() => void remove()}>删除</button>}</div></div>}</section>;
}
